### ISSUE TITLE
Non-clickable email addresses

### ISSUE THREAD

**Issue by DominikPalo** [oaki/fireblock.sk#1]
It would be nice if users are able to click on email addresses to directly compose a new email. E.g. using the `mailto:info@fireblock.sk`.

See:
https://github.com/oaki/fireblock.sk/blob/0065cf4b47b25b20211869ca19923579b55f8baa/app/presenters/templates/header.latte#L33

https://github.com/oaki/fireblock.sk/blob/0065cf4b47b25b20211869ca19923579b55f8baa/app/presenters/templates/Contact/default.latte#L48

**Comment by oaki** [comment]
Done. Thx
